### ISSUE TITLE
Freeipa manager container crashes when multiple Issuers are created in one go

### ISSUE THREAD

**Issue by globlit** [Anghille/freeipa-issuer#6]
When creating multiple issuer in a single yaml file , or single `kubectl apply` command, the freeipa container starts loop crashing without beeing able to recover

Exemple of file 

```yaml
apiVersion: certmanager.freeipa.org/v1
kind: Issuer
metadata:
  name: cert-intermediate-freeipa-issuer
  namespace: default
spec:
  hosts: 
    - ipa1.example.com
    - ipa2.example.com
  user:
    namespace: freeipa-issuer-system
    name: freeipa-issuer-freeipa-auth
    key: user
  password:
    namespace: freeipa-issuer-system
    name: freeipa-issuer-freeipa-auth
    key: password
  serviceName: HTTP
  addHost: true
  addService: true
  addPrincipal: true
  ca: other-ca
  insecure: true
  ignoreError: true
---
apiVersion: certmanager.freeipa.org/v1
kind: Issuer
metadata:
  name: cert-freeipa-issuer
  namespace: default
spec:
  hosts: 
    - ipa1.example.com
    - ipa2.example.com
  user:
    namespace: freeipa-issuer-system
    name: freeipa-issuer-freeipa-auth
    key: user
  password:
    namespace: freeipa-issuer-system
    name: freeipa-issuer-freeipa-auth
    key: password
  serviceName: HTTP
  addHost: true
  addService: true
  addPrincipal: true
  ca: ipa
  insecure: true
  ignoreError: true
```
